version: "3"
services:
  postgres:
    image: postgres:14.1-alpine
    container_name: showapp_database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    
    ports:
      - 5432:5432
    restart: always

  app:
    container_name: showapp_api
    image: registry.gitlab.com/tas11/showapp/placideh-deployment
    depends_on:
      - postgres
    
    ports:
      - "4000:3000"
    env_file:
      - ./.env
    # environment:
    #   POSTGRES_HOST: showapp_database
    #   POSTGRES_PORT: ${POSTGRES_PORT}
    #   POSTGRES_USER: ${POSTGRES_USER}
    #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #   POSTGRES_DB: ${POSTGRES_DB}
    restart: always



  
