version: "3"
services:
  postgres:
    image: postgres:14.1-alpine
    container_name: showapp_database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - showapp-network
    ports:
      - 5432:5432
    restart: always

  app:
    container_name: showapp_api
    build: .
    depends_on:
      - postgres
    networks:
      - showapp-network
    ports:
      - "4000:3000"
    environment:
      POSTGRES_HOST: showapp_database
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always

networks:
  showapp-network:


  
